### DISCUSSION TITLE
Routing on custom layer with YAML workflow

### DISCUSSION THREAD

**Discussion by Foosa7** [gdsfactory/gdsfactory#3059] [Q&A] [answered]
Dear gdsfactory friends, thank you for the wonderful software! :) I've been trying to find a way to route on a custom layer using YAML workflow, was unable to figure it out. I see that the routing takes place by default on the layer (1, 0) I want to route it at for example (10, 0) how do I do that, any help is greatly appreciated. 
 
Thank you!

```
name: routes_mmi

instances:
    mmi_bottom:
      component: mmi2x2
    mmi_top:
      component: mmi2x2

placements:
    mmi_top:
        x: 100
        y: 100

routes:
    optical:
        links:
            mmi_bottom,o4: mmi_top,o1
            mmi_bottom,o3: mmi_top,o2
```

**Comment by Foosa7** [comment, marked as answer]
I was able to figure out, the easiest way is to change the generic pdk and add settings :) 

```
name: routes_mmi

instances:
    mmi_bottom:
      component: mmi2x2
    mmi_top:
      component: mmi2x2

placements:
    mmi_top:
        x: 100
        y: 100

routes:
    optical:
        links:
            mmi_bottom,o4: mmi_top,o1
            mmi_bottom,o3: mmi_top,o2
    settings:
        cross_section: strip   
```

\Lib\site-packages\gdsfactory\generic_tech\layer_map.py

changing from WG: Layer = (1, 0) to  WG: Layer = (10, 0) did the trick. 

Thank you! Have a great day!
