### ISSUE TITLE
mirror issue in component_from_yaml

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#340]
this code has an issue

```
import gdsfactory as gf

sample_mirror = """
name: sample_mirror
instances:
    mmi1:
      component: mmi1x2

    mmi2:
      component: mmi1x2

placements:
    mmi1:
        xmax: 0

    mmi2:
        xmax: mmi1,east
        mirror: True

"""

c = gf.read.from_yaml(sample_mirror)

```

![image](https://user-images.githubusercontent.com/4514346/166459993-9c61fae7-40ce-405f-a001-86e1bcd889fd.png)

The mirror should be done before moving it to xmax
