### ISSUE TITLE
Simulation from gds-to-SAX

### ISSUE THREAD

**Issue by yangluo23** [gdsfactory/gdsfactory#3732]
Dear authors,
Thanks for your great work! 
However, is it possible to directly simulate with gdsfactory based on SAX? for example:

The following is a cell:
```python
@cell
def mzi(
    delta_length: float = 10.0,
    length_y: float = 2.0,
    length_x: float | None = 0.1,
    bend: ComponentSpec = bend_euler,
    straight: ComponentSpec = straight_function,
    straight_y: ComponentSpec | None = None,
    straight_x_top: ComponentSpec | None = None,
    straight_x_bot: ComponentSpec | None = None,
    splitter: ComponentSpec = "mmi1x2",
    combiner: ComponentSpec | None = None,
    with_splitter: bool = True,
    port_e1_splitter: str = "o2",
    port_e0_splitter: str = "o3",
    port_e1_combiner: str = "o2",
    port_e0_combiner: str = "o3",
    nbends: int = 2,
    cross_section: CrossSectionSpec = "strip",
    cross_section_x_top: CrossSectionSpec | None = None,
    cross_section_x_bot: CrossSectionSpec | None = None,
    mirror_bot: bool = False,
    add_optical_ports_arms: bool = False,
    min_length: float = 10e-3,
    auto_rename_ports: bool = True,
) -> Component:
    """Mzi.

    Args:
        delta_length: bottom arm vertical extra length.
        length_y: vertical length for both and top arms.
        length_x: horizontal length. None uses to the straight_x_bot/top defaults.
        bend: 90 degrees bend library.
        straight: straight function.
        straight_y: straight for length_y and delta_length.
        straight_x_top: top straight for length_x.
        straight_x_bot: bottom straight for length_x.
        splitter: splitter function.
        combiner: combiner function.
        with_splitter: if False removes splitter.
        port_e1_splitter: east top splitter port.
        port_e0_splitter: east bot splitter port.
        port_e1_combiner: east top combiner port.
        port_e0_combiner: east bot combiner port.
        nbends: from straight top/bot to combiner (at least 2).
        cross_section: for routing (sxtop/sxbot to combiner).
        cross_section_x_top: optional top cross_section (defaults to cross_section).
        cross_section_x_bot: optional bottom cross_section (defaults to cross_section).
        mirror_bot: if true, mirrors the bottom arm.
        add_optical_ports_arms: add all other optical ports in the arms
            with top_ and bot_ prefix.
        min_length: minimum length for the straight.
        auto_rename_ports: if True, renames ports.

    .. code::

                       b2______b3
                      |  sxtop  |
              straight_y        |
                      |         |
                      b1        b4
            splitter==|         |==combiner
                      b5        b8
                      |         |
              straight_y        |
                      |         |
        delta_length/2          |
                      |         |
                     b6__sxbot__b7
                          Lx
    """
    combiner = combiner or splitter

    straight_x_top = straight_x_top or straight
    straight_x_bot = straight_x_bot or straight
    straight_y = straight_y or straight

    cross_section_x_bot = cross_section_x_bot or cross_section
    cross_section_x_top = cross_section_x_top or cross_section
    bend = gf.get_component(bend, cross_section=cross_section)

    c = Component()
    cp1 = gf.get_component(splitter)
    cp2 = gf.get_component(combiner) if combiner else cp1

    if with_splitter:
        cp1 = c << cp1
        cp1.name = "cp1"

    cp2 = c << cp2
    b5 = c << bend
    b5.connect("o1", cp1.ports[port_e0_splitter], mirror=True)

    syl = c << gf.get_component(
        straight_y, length=delta_length / 2 + length_y, cross_section=cross_section
    )
    syl.connect("o1", b5.ports["o2"])
    b6 = c << bend
    b6.connect("o1", syl.ports["o2"], mirror=True)

    straight_x_top = (
        gf.get_component(
            straight_x_top, length=length_x, cross_section=cross_section_x_top
        )
        if length_x
        else gf.get_component(straight_x_top)
    )
    sxt = c << straight_x_top

    length_x = length_x or abs(sxt.ports["o1"].dx - sxt.ports["o2"].dx)

    straight_x_bot = (
        gf.get_component(
            straight_x_bot, length=length_x, cross_section=cross_section_x_bot
        )
        if length_x
        else gf.get_component(straight_x_bot)
    )
    sxb = c << straight_x_bot
    sxb.connect("o1", b6.ports["o2"], mirror=mirror_bot)

    b1 = c << bend
    b1.connect("o1", cp1.ports[port_e1_splitter])

    sytl = c << gf.get_component(
        straight_y, length=length_y, cross_section=cross_section
    )
    sytl.connect("o1", b1.ports["o2"])

    b2 = c << bend
    b2.connect("o2", sytl.ports["o2"])

    sxt.connect("o1", b2.ports["o1"])

    cp2.mirror_x()
    cp2.dxmin = sxt.ports["o2"].dx + bend.info["radius"] * nbends + 2 * min_length

    route_single(
        c,
        cp2.ports[port_e1_combiner],
        sxt.ports["o2"],
        straight=straight,
        bend=bend,
        cross_section=cross_section,
        taper=None,
    )
    route_single(
        c,
        cp2.ports[port_e0_combiner],
        sxb.ports["o2"],
        straight=straight,
        bend=bend,
        cross_section=cross_section,
        taper=None,
    )

    sytl.name = "sytl"
    syl.name = "syl"
    sxt.name = "sxt"
    sxb.name = "sxb"
    cp2.name = "cp2"

    if with_splitter:
        c.add_ports(cp1.ports.filter(orientation=180), prefix="in_")
    else:
        c.add_port("o1", port=b1.ports["o1"])
        c.add_port("o2", port=b5.ports["o1"])
    c.add_ports(cp2.ports.filter(orientation=0), prefix="ou_")
    c.add_ports(sxt.ports.filter(port_type="electrical"), prefix="top_")
    c.add_ports(sxb.ports.filter(port_type="electrical"), prefix="bot_")
    c.add_ports(sxt.ports.filter(port_type="placement"), prefix="top_")
    c.add_ports(sxb.ports.filter(port_type="placement"), prefix="bot_")

    # c.auto_rename_ports(port_type="optical", prefix="o")

    if add_optical_ports_arms:
        c.add_ports(sxt.ports.filter(port_type="optical"), prefix="top_")
        c.add_ports(sxb.ports.filter(port_type="optical"), prefix="bot_")

    if auto_rename_ports:
        c.auto_rename_ports()
    return c
```

Then if I want to simulate its S-parameter, I first need to get its nelist:

```python
    c = mzi()
    netlist = c.get_netlist(recursive=True)
```

but for SAX, we should identify the `models`:  
```python
circuit, _ = sax.circuit(netlist=netlist, models=models)
```
So, how should I get that models in the pre-defined mzi cell? I think it is the same as [issue](https://github.com/gdsfactory/gdsfactory/issues/1067#issue-1516866413//)

**Comment by yangluo23** [comment]
Oh, thanks for your reply.

Yes, I can add such model definition by myself. But how can I directly get that models (in the netlist) just from gdsfactory?
If I write this netlist into yaml:
```yaml
mzi_DL10_LY2_LX0p1_Bben_7a5bab35:
  connections:
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-22750,o1: sxb,o2
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-22750,o2: straight_L7_N2_CSstrip_W0p5_5400_-14125,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-5500,o1: straight_L7_N2_CSstrip_W0p5_5400_-14125,o2
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-5500,o2: straight_L40p22_N2_CSstrip_W0p5_35510_-625,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-22750,o1: syl,o2
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-22750,o2: sxb,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-5500,o1: cp1,o3
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-5500,o2: syl,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_5500,o1: cp1,o2
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_5500,o2: sytl,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_30375_17750,o1: sxt,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_30375_17750,o2: sytl,o2
    bend_euler_RNone_A90_P0_d7c3a5a9_40745_17750,o1: straight_L0p02_N2_CSstrip_W0p5_35610_22625,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_40745_17750,o2: straight_L2_N2_CSstrip_W0p5_45620_11625,o1
    bend_euler_RNone_A90_P0_d7c3a5a9_50495_5500,o1: straight_L2_N2_CSstrip_W0p5_45620_11625,o2
    bend_euler_RNone_A90_P0_d7c3a5a9_50495_5500,o2: cp2,o2
    cp2,o3: straight_L40p22_N2_CSstrip_W0p5_35510_-625,o2
    straight_L0p02_N2_CSstrip_W0p5_35610_22625,o2: sxt,o2
  instances:
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-22750:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-5500:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-22750:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-5500:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_5500:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    bend_euler_RNone_A90_P0_d7c3a5a9_30375_17750:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    bend_euler_RNone_A90_P0_d7c3a5a9_40745_17750:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    bend_euler_RNone_A90_P0_d7c3a5a9_50495_5500:
      component: bend_euler
      info:
        length: 16.637
        dy: 10
        min_bend_radius: 7.061
        radius: 10
        route_info_type: xs_34e31a19
        route_info_length: 16.637
        route_info_weight: 16.637
        route_info_xs_34e31a19_length: 16.637
        route_info_n_bend_90: 1
        route_info_min_bend_radius: 7.061
      settings:
        angle: 90
        p: 0.5
        with_arc_floorplan: true
        cross_section: strip
        allow_min_radius_violation: false
    cp1:
      component: mmi1x2
      info: {}
      settings:
        width_taper: 1
        length_taper: 10
        length_mmi: 5.5
        width_mmi: 2.5
        gap_mmi: 0.25
        taper: taper
        straight: straight
        cross_section: strip
    cp2:
      component: mmi1x2
      info: {}
      settings:
        width_taper: 1
        length_taper: 10
        length_mmi: 5.5
        width_mmi: 2.5
        gap_mmi: 0.25
        taper: taper
        straight: straight
        cross_section: strip
    straight_L0p02_N2_CSstrip_W0p5_35610_22625:
      component: straight
      info:
        length: 0.02
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 0.02
        route_info_weight: 0.02
        route_info_xs_34e31a19_length: 0.02
      settings:
        length: 0.02
        npoints: 2
        cross_section: strip
        width: 0.5
    straight_L2_N2_CSstrip_W0p5_45620_11625:
      component: straight
      info:
        length: 2
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 2
        route_info_weight: 2
        route_info_xs_34e31a19_length: 2
      settings:
        length: 2
        npoints: 2
        cross_section: strip
        width: 0.5
    straight_L40p22_N2_CSstrip_W0p5_35510_-625:
      component: straight
      info:
        length: 40.22
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 40.22
        route_info_weight: 40.22
        route_info_xs_34e31a19_length: 40.22
      settings:
        length: 40.22
        npoints: 2
        cross_section: strip
        width: 0.5
    straight_L7_N2_CSstrip_W0p5_5400_-14125:
      component: straight
      info:
        length: 7
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 7
        route_info_weight: 7
        route_info_xs_34e31a19_length: 7
      settings:
        length: 7
        npoints: 2
        cross_section: strip
        width: 0.5
    sxb:
      component: straight
      info:
        length: 0.1
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 0.1
        route_info_weight: 0.1
        route_info_xs_34e31a19_length: 0.1
      settings:
        length: 0.1
        npoints: 2
        cross_section: strip
    sxt:
      component: straight
      info:
        length: 0.1
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 0.1
        route_info_weight: 0.1
        route_info_xs_34e31a19_length: 0.1
      settings:
        length: 0.1
        npoints: 2
        cross_section: strip
    syl:
      component: straight
      info:
        length: 7
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 7
        route_info_weight: 7
        route_info_xs_34e31a19_length: 7
      settings:
        length: 7
        npoints: 2
        cross_section: strip
    sytl:
      component: straight
      info:
        length: 2
        width: 0.5
        route_info_type: xs_34e31a19
        route_info_length: 2
        route_info_weight: 2
        route_info_xs_34e31a19_length: 2
      settings:
        length: 2
        npoints: 2
        cross_section: strip
  placements:
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-22750:
      x: 15.4
      'y': -27.625
      rotation: 180
      mirror: true
    bend_euler_RNone_A90_P0_d7c3a5a9_10275_-5500:
      x: 5.4
      'y': -10.625
      rotation: 90
      mirror: true
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-22750:
      x: 25.5
      'y': -17.625
      rotation: 270
      mirror: true
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_-5500:
      x: 15.5
      'y': -0.625
      rotation: 0
      mirror: true
    bend_euler_RNone_A90_P0_d7c3a5a9_20625_5500:
      x: 15.5
      'y': 0.625
      rotation: 0
      mirror: false
    bend_euler_RNone_A90_P0_d7c3a5a9_30375_17750:
      x: 35.5
      'y': 22.625
      rotation: 180
      mirror: false
    bend_euler_RNone_A90_P0_d7c3a5a9_40745_17750:
      x: 35.62
      'y': 22.625
      rotation: 0
      mirror: true
    bend_euler_RNone_A90_P0_d7c3a5a9_50495_5500:
      x: 45.62
      'y': 10.625
      rotation: 270
      mirror: false
    cp1:
      x: 0
      'y': 0
      rotation: 0
      mirror: false
    cp2:
      x: 71.12
      'y': 0
      rotation: 180
      mirror: true
    straight_L0p02_N2_CSstrip_W0p5_35610_22625:
      x: 35.62
      'y': 22.625
      rotation: 180
      mirror: false
    straight_L2_N2_CSstrip_W0p5_45620_11625:
      x: 45.62
      'y': 12.625
      rotation: 270
      mirror: false
    straight_L40p22_N2_CSstrip_W0p5_35510_-625:
      x: 15.4
      'y': -0.625
      rotation: 0
      mirror: false
    straight_L7_N2_CSstrip_W0p5_5400_-14125:
      x: 5.4
      'y': -17.625
      rotation: 90
      mirror: false
    sxb:
      x: 15.5
      'y': -27.625
      rotation: 180
      mirror: false
    sxt:
      x: 35.5
      'y': 22.625
      rotation: 0
      mirror: false
    syl:
      x: 25.5
      'y': -10.625
      rotation: 270
      mirror: false
    sytl:
      x: 25.5
      'y': 10.625
      rotation: 90
      mirror: false
  ports:
    o1: cp1,o1
    o2: cp2,o1
  name: mzi_DL10_LY2_LX0p1_Bben_7a5bab35
```

So, follow this file,  each component is a model. But how I get its model value as the same as customed model object?
```python
def mzi(*args, **kwargs) -> sax.SDict:
    <parametric ...>
    sparam_dict = sax.reciprocal(
        {
            ("in0", "out0"): <value>,
            ...
        }
    )
    return sparam_dict 
```
